### ISSUE TITLE
Replace clinical note schema by a standard schema

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/nlp-sandbox-schemas#35]
The current definition of a clinical note is available:
https://github.com/Sage-Bionetworks/nlp-sandbox-schemas/blob/develop/openapi/commons/components/schemas/Note.yaml

This format is largely inspired from the format of the 2014 i2b2 dataset. This was great to get the 2014 i2b2 Data Node working more quickly. Ultimately we want to adopt a more standard format that hospital and other data sites are more likely to use. Relying on this more standard definition of a clinical note would make the NLP Tool easier to use on clinical notes that follow this standard. A could place to look for a candidate schema is FHIR.

## Task

- Identify if FHIR has a schema for clinical notes
- Identify the schemas used by Google de-id and Amazon Comprehend
- Create a PR that modifies our definition of the note object to match a standard note schema

**Comment by tschaffter** [comment]
@ymnliu Can you please take care of this ticket? Let me know if you have any question. Thanks!

**Comment by ymnliu** [comment]
I am sure some of the fields in the current schema are required by OpenAPI, but my knowledge is limited on that. I am putting the FHIR reference here: https://www.hl7.org/fhir/documentreference.html for further discussion.

**Comment by tschaffter** [comment]
@cascadianblue Can you weight in by sharing with us here the schema that Google de-id service and Amazon Comprehend use to represent clinical note? Do they rely on a standard schema or is it custom?

**Comment by tschaffter** [comment]
Also shall we name this schema Note (current name) or something else (e.g. record).

This paper that describes the preparation of the 2014 i2b2 dataset has only 5 occurrences of the the work "note" and 80 occurrences of the word "record".

@gkowalski @ymnliu Thoughts?

**Comment by cascadianblue** [comment]
Google Healthcare uses FHIR; it looks like there actually is some standard specifically on how to use FHIR to represent [clinical notes](https://build.fhir.org/ig/HL7/US-Core-R4/clinical-notes-guidance.html#clinical-notes). Amazon Comprehend Medical [just has a "text" field](https://docs.aws.amazon.com/comprehend/latest/dg/API_medical_DetectPHI.html) for you to dump your note contents into.

**Comment by tschaffter** [comment]
From [FHIR Clinical Notes Guidance](https://build.fhir.org/ig/HL7/US-Core-R4/clinical-notes-guidance.html#clinical-notes):

- I will rename our Note schema to ClinicalNote to be more descriptive and support in the future non-clinical notes
- A loinc URL is used as note type, e.g. https://loinc.org/11488-4.html/.
   - FHIR encourages systems to support “5 Common Clinical Notes” and "3 DiagnosticReport categories"
- Two partially overlapping types of documents:
  - DocumentReference (content location: DocumentReference.content.attachment.url)
  - DiagnosticReport (content location: DiagnosticReport.presentedForm.url)
- The schema adopted by FHIR enables the client to know the type of document content the URL is pointing to (e.g. json, PDF)
- Recommends to systems to support these three types of report categories:
  - Cardiology (LP29708-2)
  - Pathology (LP7839-6)
  - Radiology (LP29684-5)
- FHIR has a standard search API for retrieving clinical notes and reports

> There is no single best practice for representing a scanned, or narrative-only report due to the overlapping scope of the underlying resources and variability in system implementation. Reports may be represented by either a DocumentReference or a DiagnosticReport as demonstrated by the green area in Figure 1. For example, some systems consider any scanned report, or note, a DocumentReference. Other systems allow users to categorize the scanned report as Lab and store to DiagnosticReport.

**Comment by tschaffter** [comment]
Related to https://github.com/Sage-Bionetworks/nlp-sandbox-data-node-i2b2-2014/issues/72

**Comment by tschaffter** [comment]
The data node now offers to create a light FHIR store. Two types of objects can be pushed to this store; FHIR Patient (partial representation) and a custom Note object.
