### ISSUE TITLE
What is the types of notes in the i2b2 dataset?

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/nlp-sandbox-schemas#56]
@gkowalski Pahtology? Phone call?

Then set Note.type accordingly

**Comment by gkowalski** [comment]
I can pull a standard list from EPIC , but I think it's like 100 - 200 types ( need to determine if I can release that ) . We also have. a curated list of the top ( buy importance ) our Business analysts have come up with that we use to deliver notes and use for prioritizing deidentification Jobs.

**Comment by gkowalski** [comment]
I've been given permissions to release the top 45 note types that we use . We will have to add others like Gold standard , testing , etc. I'll email to the group for review.

**Comment by tschaffter** [comment]
Thanks @gkowalski. In your email you mention:

> These are standard note types

Do you know where I can find the official page for this standard? We can use unique identifier from this page to build a list of enumeration that we use to validate Tools.

Regarding the 2014 i2b2 dataset, they don't seem to mention the type of notes.

> The corpus selected for this project consisted of the longitudinal records for 301 patients, with 2–5 records selected per patient. The records came from Partners Healthcare, and were selected for use in Track 2 of the i2b2/UTHealth shared task: identification of risk factors for Cardiac Artery Disease in diabetic patients (Stubbs et al., this issue, 2015b). The records for each patient represent a snapshot of the patient’s health at different points in time, not the patient’s full medical history. The complete details of the corpus selection process are described in Kumar et al. (this issue). Over the course of the de-identification annotation, we had to remove some records from the corpus as they were incompatible with our surrogate generation software due to improper character encodings. The final corpus contains sets of longitudinal records for 296 patients, a total of 1,304 individual records, with 805,118 whitespace-separated tokens; an average of 617.4 tokens per file.

[Source ](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4978170/)

We would then specify the type "Other" or the corresponding code in the standard you mentioned.

**Comment by gkowalski** [comment]
Sorry the ticket is for "i2b2 dataset" and I was sending around top note types for an EHR. Those in the 2014 challenge , as they are not real in any way and could be considered "Test" or "System Validation" , something like that .

**Comment by gkowalski** [comment]
THere is no standard on note types we've found, These are used by our  EHR , Their documentation is copyright and can't be released.

**Comment by tschaffter** [comment]
We do not know the type of notes. The property Note.noteType is going to be left blank for the i2b2 dataset.
