### ISSUE TITLE
List annotation stores returns name but with a typo

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/nlp-sandbox-schemas#88]
```
curl -X GET "http://10.23.55.45:8080/api/v1/datasets/awesome-dataset/annotationStore?limit=10" -H  "accept: application/json"
{
  "annotationStores": [
    {
      "name": "datasets/awesome-dataset/annotationStores/awesome-annotation-store"
    }
  ],
  "limit": 10,
  "links": {
    "next": ""
  },
  "offset": 0
}
```

It should be `annotationStore` not `annotationStores`

**Comment by tschaffter** [comment]
API paths are usually in the plural form. Thus the typo is actually in `http://10.23.55.45:8080/api/v1/datasets/awesome-dataset/annotationStore?limit=10`. The only exception in this API are the FHIR paths like `../fhir/Patient`.

https://fhir-drills.github.io/simple-patient.html

> The official URL for this operation definition is
>  http://hl7.org/fhir/OperationDefinition/Observation-stats (see https://hl7.org/fhir/2018Jan/observation-operations.html)

**Comment by thomasyu888** [comment]
Ah, I see.  Then the typo needs to be changed for annotationStores.

![image](https://user-images.githubusercontent.com/10556275/99929821-9647f600-2d89-11eb-8b59-3dfdbe21d027.png)
